---
- name: Nginx telepítés és konfigurálása
  hosts: web
  become: yes

  vars:
    index_message: "<h1>Szabó Bence István</h1>"

  tasks:
    - name: Nginx telepítés
      ansible.builtin.dnf:
        name: nginx
        state: present

    - name: Deploy index.html
      ansible.builtin.template:
        src: templates/index.html.j2
        dest: /usr/share/nginx/html/index.html
        owner: root
        group: root
        mode: "0644"
      notify: Restart nginx

    - name: Enable and start nginx
      ansible.builtin.service:
        name: nginx
        enabled: yes
        state: started
    - name: Firewalld check
      ansible.builtin.dnf:
        name: firewalld
        state: present

    - name: Firewalld futás check
      ansible.builtin.service:
        name: firewalld
        enabled: yes
        state: started

    - name: Allow HTTP
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true

  handlers:
    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
